version: "3.7"
services:
  postgres:
    image: postgres:10
    volumes:
      - .pgdata:/var/lib/postgresql/data
    env_file: .env
    build:
      context: ./postgres

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "8000:8000"
