# Generated by Django 2.0.2 on 2021-07-11 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('PAGO CONTRAENTREGA', 'PAGO CONTRAENTREGA'), ('TARJETA CRÉDITO', 'TARJETA CRÉDITO'), ('TARJETA DÉBITO', 'TARJETA DÉBITO'), ('PAYPAL', 'PAYPAL'), ('PSE', 'PSE')], default='OTRO', max_length=50, verbose_name='Opcion de pago')),
                ('payment_total', models.PositiveIntegerField(verbose_name='Total a pagar')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_payment_order', models.PositiveIntegerField(verbose_name='Pago total de la orden')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Subtotal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='Orden de venta')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Payment', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle del pago',
                'verbose_name_plural': 'Detalle de los pagos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='paymentorder',
            unique_together={('order', 'payment')},
        ),
    ]
